# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/Documents/Projects/madNES

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/Documents/Projects/madNES

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/Documents/Projects/madNES/CMakeFiles /home/daniel/Documents/Projects/madNES//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/Documents/Projects/madNES/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named madNES

# Build rule for target.
madNES: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 madNES
.PHONY : madNES

# fast build rule for target.
madNES/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/build
.PHONY : madNES/fast

src/cpu.o: src/cpu.cpp.o
.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i
.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s
.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/game_loop.o: src/game_loop.cpp.o
.PHONY : src/game_loop.o

# target to build an object file
src/game_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/game_loop.cpp.o
.PHONY : src/game_loop.cpp.o

src/game_loop.i: src/game_loop.cpp.i
.PHONY : src/game_loop.i

# target to preprocess a source file
src/game_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/game_loop.cpp.i
.PHONY : src/game_loop.cpp.i

src/game_loop.s: src/game_loop.cpp.s
.PHONY : src/game_loop.s

# target to generate assembly for a file
src/game_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/game_loop.cpp.s
.PHONY : src/game_loop.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mappers.o: src/mappers.cpp.o
.PHONY : src/mappers.o

# target to build an object file
src/mappers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/mappers.cpp.o
.PHONY : src/mappers.cpp.o

src/mappers.i: src/mappers.cpp.i
.PHONY : src/mappers.i

# target to preprocess a source file
src/mappers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/mappers.cpp.i
.PHONY : src/mappers.cpp.i

src/mappers.s: src/mappers.cpp.s
.PHONY : src/mappers.s

# target to generate assembly for a file
src/mappers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/mappers.cpp.s
.PHONY : src/mappers.cpp.s

src/parse_args.o: src/parse_args.cpp.o
.PHONY : src/parse_args.o

# target to build an object file
src/parse_args.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/parse_args.cpp.o
.PHONY : src/parse_args.cpp.o

src/parse_args.i: src/parse_args.cpp.i
.PHONY : src/parse_args.i

# target to preprocess a source file
src/parse_args.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/parse_args.cpp.i
.PHONY : src/parse_args.cpp.i

src/parse_args.s: src/parse_args.cpp.s
.PHONY : src/parse_args.s

# target to generate assembly for a file
src/parse_args.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/parse_args.cpp.s
.PHONY : src/parse_args.cpp.s

src/parse_rom.o: src/parse_rom.cpp.o
.PHONY : src/parse_rom.o

# target to build an object file
src/parse_rom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/parse_rom.cpp.o
.PHONY : src/parse_rom.cpp.o

src/parse_rom.i: src/parse_rom.cpp.i
.PHONY : src/parse_rom.i

# target to preprocess a source file
src/parse_rom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/parse_rom.cpp.i
.PHONY : src/parse_rom.cpp.i

src/parse_rom.s: src/parse_rom.cpp.s
.PHONY : src/parse_rom.s

# target to generate assembly for a file
src/parse_rom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/madNES.dir/build.make CMakeFiles/madNES.dir/src/parse_rom.cpp.s
.PHONY : src/parse_rom.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... madNES"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/game_loop.o"
	@echo "... src/game_loop.i"
	@echo "... src/game_loop.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mappers.o"
	@echo "... src/mappers.i"
	@echo "... src/mappers.s"
	@echo "... src/parse_args.o"
	@echo "... src/parse_args.i"
	@echo "... src/parse_args.s"
	@echo "... src/parse_rom.o"
	@echo "... src/parse_rom.i"
	@echo "... src/parse_rom.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

